### ISSUE TITLE
Problem running indeMINER

### ISSUE THREAD

**Issue by Addicted-to-coding** [aakrosh/indelMINER#8]
When I run indelMINER with the test data, it works fine but when I use my reference genome and bam file from mouse ch19, i get the error Assertion failed: indx == hin->n_targets file shared.c line 77
The format of my bam file is
HS19_07713:4:2306:10325:100417#86       99      19      3000084 0       100M    =       3000325 341     CTATGCCAGTTATGCATAATGCACAAATATTTCCACGCTTTTTCACTACAGATAAAGAACTGGGACTTGCTTATTTACCTTTAGATGAACAGATTCAGGC    BACADGFFEIGHHFGHHHFHF<HFHFHHFEGHGHGGIIGHGDCHFGFFJHHGFGHGAFHFGFHFAFFEGGEFHIJFEFEFGIF5EJ5BGEE4DGDBD+3(    MD:Z:100        RG:Z:7713_4#86  NM:i:0  MQ:i:0  AS:i:100        XS:i:100        CT:Z:1F100M141T2R100M

which is very similar to the test bam file
How can I fix this and get the tool to work?

**Comment by aakrosh** [comment]
The assert fails if the number of contigs in the reference fasta file (ref.fa) and the number of contigs in the BAM file (aln.bam) are different, which is a signal that a different reference was used for the alignments. 

You should be able to check the number of contigs in the ref.fa file by running the following:
```bash
grep -c ">" ref.fa
```

Similarly you should be able to check the number of contigs in the BAM file by running the following:
```bash
samtools view -H aln.bam | grep -c "^@SQ"
```

**Comment by Addicted-to-coding** [comment]
Thanks for the help, it works now!!

Varuni Sarwal
Undergraduate researcher at Zarlab , http://zarlab.cs.ucla.edu/
Department of Computer Science
University of California, Los Angeles
Indian Institute of Technology
New Delhi
