### ISSUE TITLE
Memory error while running indelMINER

### ISSUE THREAD

**Issue by aditya-sarkar441** [aakrosh/indelMINER#9]
I am working with indelMINER on one of my projects. But the problem is that it is giving error: "ckrealloc failed" and giving empty .vcf files. This is when I allocated it 64GB in HPC. I also tried with 128GB but no improvement. What could be the possible cause for this error?
PS : The bams are of size 35GB.

**Comment by aakrosh** [comment]
Thanks for reporting the issue. Can you please paste the complete output (to the screen or stderr) generated by indelMINER?  That would help understand where it fails.

**Comment by aditya-sarkar441** [comment]
![Screenshot 2020-11-14 at 12 59 05 AM](https://user-images.githubusercontent.com/56690786/99113119-bc94c580-2614-11eb-9000-62182f396b74.png)
![Screenshot 2020-11-14 at 12 58 45 AM](https://user-images.githubusercontent.com/56690786/99113135-c0284c80-2614-11eb-963c-7f918869d2d6.png)

@aakrosh Here are the outputs.

**Comment by aditya-sarkar441** [comment]
This is with 64GB.

**Comment by aakrosh** [comment]
Thanks. Based on the output, it appears that indelMINER is running into allocation issues while reading your reference sequence. Could you point me to the reference genome you are using?

**Comment by aditya-sarkar441** [comment]
@aakrosh You want the fasta file ?

**Comment by aakrosh** [comment]
Could you point me to the fasta file on Genbank that you are using as reference? If it is not available there, then could you send me the fai index file (http://www.htslib.org/doc/faidx.html)

**Comment by aditya-sarkar441** [comment]
Can you give me sometime? I have to ask my PhD mentor before sharing it.

**Comment by aditya-sarkar441** [comment]
@aakrosh Here is the fai index file. It's in the zip folder.
[fasta.fai.zip](https://github.com/ratan-lab/indelMINER/files/5540743/fasta.fai.zip)

**Comment by aakrosh** [comment]
Thank you. Can you please tell me the output of the following command?

```{bash}
head -n 1 fasta.fa
```

**Comment by aditya-sarkar441** [comment]
>chr1  AC:CM000663.2  gi:568336023  LN:248956422  rl:Chromosome  M5:6aef897c3d6ff0c78aff06ac189178dd  AS:GRCh38

@aakrosh It's showing this.

**Comment by aditya-sarkar441** [comment]
@aakrosh did you find anything ?

**Comment by aakrosh** [comment]
I am able to read an equivalent reference genome (hg38, the same one you use) with ~3 GB of memory without any problems, so I am not sure what the problem is in reading the reference (which should be the next step). However, based on the output of the program you paste above, I believe indelMINER might not be the appropriate method for your dataset. Based on the output I see above, it seems that the aligner marks pairs with insert lengths between 20 bp - 2000 bps as being "proper". This implementation could require large chunks of memory to handle datasets with such wide range of insert lengths.

**Comment by aditya-sarkar441** [comment]
@aakrosh I think 128 GB should work. It is not working with that as well. Does it require more memory ?

**Comment by aditya-sarkar441** [comment]
@aakrosh can you suggest us some way to run IndelMINER on the bams ?

The bams are of size 30 GB and we are working on HPC.

**Comment by aakrosh** [comment]
Based on the output regarding insert lengths generated by indelMINER, I think it is not appropriate for your dataset . I would recommend you use some other method such as LUMPY (https://github.com/arq5x/lumpy-sv), SVABA (https://github.com/walaj/svaba) or SVXplorer (https://github.com/kunalkathuria/SVXplorer).

**Comment by aditya-sarkar441** [comment]
@aakrosh  Ok thanks !! Will look into it.
